apiVersion: batch/v1
kind: Job
metadata:
  name: i3o-patch
  namespace: traefik-mesh
  labels:
    app: {{ .Release.Name | quote}}
    chart: {{ include "i3o.chartLabel" . | quote }}
    release: {{ .Release.Name | quote}}
    heritage: {{ .Release.Service | quote}}
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "hook-succeeded,before-hook-creation"
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 60
  template:
    metadata:
      labels:
        app: {{ .Release.Name | quote}}
        component: patch
        release: {{ .Release.Name | quote}}
    spec:
      serviceAccountName: i3o-patch
      restartPolicy: Never
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- end }}
      containers:
        - name: i3o-patch
          image: {{ include "i3o.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent"}}
          args:
            - "patch"
          securityContext:
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
