## Default values for maesh
controller:
  image:
    name: containous/maesh
    # (Optional)
    pullPolicy: IfNotPresent
    # (Optional)
    tag: latest
    # (Optional)
    # pullSecret: xxx
  resources:
    limit:
      mem: "100Mi"
      cpu: "200m"
    request:
      mem: "50Mi"
      cpu: "100m"
  logging:
    debug: true


mesh:
  image:
    name: traefik
    # (Optional)
    # pullPolicy: IfNotPresent
    # (Optional)
    tag: v2.0.2
    # (Optional)
    # pullSecret: xxx
  resources:
    limit:
      mem: "100Mi"
      cpu: "200m"
    request:
      mem: "50Mi"
      cpu: "100m"
  logging: ERROR
  defaultMode: http

#
# addon jaeger tracing configuration
#
tracing:
  deploy: false
  jaeger:
    enabled: false
    localagenthostport: ""
    samplingserverurl: ""

#
# addon metrics configuration
#
metrics:
  deploy: false
  prometheus:
    enabled: false

smi:
  deploy: false
  enable: false

kubedns: false

limits:
  http: 10
  tcp: 25
