apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: i3o-mesh
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name | quote }}
    chart: {{ include "i3o.chartLabel" . | quote }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  serviceAccountName: i3o-mesh
  selector:
    matchLabels:
      app: {{ .Release.Name | quote }}
      component: mesh
      release: {{ .Release.Name | quote }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name | quote }}
        component: mesh
        release: {{ .Release.Name | quote }}
    spec:
      terminationGracePeriodSeconds: 30
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- end }}
      containers:
        - name: i3o-mesh
          image: {{ .Values.image.traefik | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          args:
            - "providers.kubernetescrd"
            - "providers.kubernetescrd.labelselector='i3o-mesh=internal'"
          securityContext:
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
          
