apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: i3o-mesh
  namespace: traefik-mesh
  labels:
    app: {{ .Release.Name | quote }}
    chart: {{ include "i3o.chartLabel" . | quote }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name | quote }}
      component: i3o-mesh
      release: {{ .Release.Name | quote }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name | quote }}
        component: i3o-mesh
        release: {{ .Release.Name | quote }}
    spec:
      serviceAccountName: i3o-mesh
      terminationGracePeriodSeconds: 30
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- end }}
      containers:
        - name: i3o-mesh
          image: {{ .Values.image.traefik | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          args:
            - "--entryPoints.ingress-5000.address=:5000"
            - "--entryPoints.ingress-5001.address=:5001"
            - "--entryPoints.ingress-5002.address=:5002"
            - "--entryPoints.ingress-5003.address=:5003"
            - "--entryPoints.ingress-5004.address=:5004"
            - "--entryPoints.ingress-5005.address=:5005"
            - "--entryPoints.ingress-5006.address=:5006"
            - "--entryPoints.ingress-5007.address=:5007"
            - "--entryPoints.ingress-5008.address=:5008"
            - "--entryPoints.ingress-5009.address=:5009"
            - "--providers.kubernetescrd"
            - "--providers.kubernetescrd.labelselector=i3o-mesh=internal"
            - "--tracing.backend=jaeger"
            - "--tracing.jaeger.localagenthostport=jaeger-agent.{{ .Release.Namespace }}.svc.cluster.local"
            - "--api.dashboard"
            - "--accesslog"
          securityContext:
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
          
