## Default values for maesh
controller:
  image:
    name: containous/maesh
    # (Optional)
    # pullPolicy: IfNotPresent
    # (Optional)
    # tag: v0.0.1
    # (Optional)
    # pullSecret: xxx
  resources:
    limit:
      mem: "100Mi"
      cpu: "200m"
    request:
      mem: "50Mi"
      cpu: "100m"
  logging:
    debug: true
  ignoreNamespaces:
  # Added so we can launch on nodes with restrictions
  nodeSelector: {}
  tolerations: []
  affinity: {}

kubedns: false
#clusterDomain: cluster.local

mesh:
  image:
    name: traefik
    # (Optional)
    # pullPolicy: IfNotPresent
    # (Optional)
    # tag: v2.0
    # (Optional)
    # pullSecret: xxx
  resources:
    limit:
      mem: "100Mi"
      cpu: "200m"
    request:
      mem: "50Mi"
      cpu: "100m"
  logging: INFO
  defaultMode: http
  # Added so we can launch on nodes with restrictions
  nodeSelector: {}
  tolerations: []

#
# addon jaeger tracing configuration
#
tracing:
  deploy: true
  jaeger:
    image:
      name: groundnuty/k8s-wait-for:v1.2
    enabled: true
    localagenthostport: ""
    samplingserverurl: ""

#
# addon metrics configuration
#
metrics:
  deploy: true
  prometheus:
    # whether to expose Prometheus metrics
    enabled: true
  ## you can override values of the metrics subchart here.
  ## check charts/metrics/values.yaml for the defaults.
  ## example:
  # grafana:
  #   storageClassName: "metrics-storage"
  #   resources:
  #     limit:
  #       mem: "500Mi"
  #       cpu: "500m"
  #     request:
  #       mem: "200Mi"
  #       cpu: "200m"

smi:
  deploycrds: true
  enable: false

limits:
  http: 10
  tcp: 25
