## Default values for maesh
controller:
  image:
    name: containous/maesh
    # (Optional)
    # pullPolicy: IfNotPresent
    # (Optional)
    # tag: v0.0.1
    # (Optional)
    # pullSecret: xxx
  resources:
    limit:
      mem: "100Mi"
      cpu: "200m"
    request:
      mem: "50Mi"
      cpu: "100m"
  logging:
    debug: true
  ignoreNamespaces:
  # Added so we can launch on nodes with restrictions
  nodeSelector: {}
  tolerations: []
  affinity: {}

mesh:
  image:
    name: traefik:v2.0.0-rc1
    # (Optional)
    # pullPolicy: IfNotPresent
    # (Optional)
    # tag: v0.0.1
    # (Optional)
    # pullSecret: xxx
  resources:
    limit:
      mem: "100Mi"
      cpu: "200m"
    request:
      mem: "50Mi"
      cpu: "100m"
  logging: INFO
  defaultMode: http
  # Added so we can launch on nodes with restrictions
  tolerations: []

#
# addon jaeger tracing configuration
#
tracing:
  enabled: true

#
# addon metrics configuration
#
metrics:
  enabled: true

smi: false

limits:
  http: 10
  tcp: 25
