apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tiny-tools
  namespace: default
  labels:
    app: tiny-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tiny-tools
  template:
    metadata:
      name: tiny-tools
      namespace: default
      labels:
        app: tiny-tools
    spec:
      containers:
      - name: tiny-tools
        image: giantswarm/tiny-tools:3.9
        command:
        - "sleep"
        - "3600"
