## Default values for i3o
image:
  name: containous/i3o
  # (Optional)
  # pullPolicy: IfNotPresent
  # (Optional)
  # tag: v0.0.1
  # (Optional)
  # pullSecret: xxx
  traefik: traefik:v2.0.0-beta1

debug: true

# mesh:
#   defaultMode: http

#
# addon jaeger tracing configuration
#
tracing:
  enabled: true

metrics:
  enabled: true

smi: false
