---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: grafana
  labels:
    app: maesh
    component: grafana
    chart: {{ include "traefikMesh.chartLabel" . | quote }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: maesh
      component: grafana
