---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: maesh-mesh
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name | quote }}
    chart: {{ include "maesh.chartLabel" . | quote }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  {{- with .Values.mesh.annotations }}
  annotations:
{{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name | quote }}
      component: maesh-mesh
      release: {{ .Release.Name | quote }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name | quote }}
        component: maesh-mesh
        release: {{ .Release.Name | quote }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        {{- with .Values.mesh.podAnnotations }}
{{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: maesh-mesh
      automountServiceAccountToken: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      terminationGracePeriodSeconds: 30
      {{- if .Values.mesh.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.mesh.image.pullSecret }}
      {{- end }}
      {{- with .Values.mesh.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.mesh.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- if .Values.tracing.deploy }}
      initContainers:
        - name: wait-for-jaeger-init
          image: {{ .Values.tracing.jaeger.image.name | quote }}
          imagePullPolicy: {{ .Values.tracing.jaeger.image.pullPolicy | default "IfNotPresent" }}
          args:
            - "service"
            - "-lapp.kubernetes.io/name=jaeger,app.kubernetes.io/component=agent"
          resources:
            requests:
              memory: "10Mi"
              cpu: "50m"
            limits:
              memory: "20Mi"
              cpu: "100m"
      {{- end }}
      containers:
        - name: maesh-mesh
          image: {{ include "maesh.meshImage" . | quote }}
          imagePullPolicy: {{ .Values.mesh.image.pullPolicy | default "IfNotPresent" }}
          {{- with .Values.mesh.env }}
          env:
{{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.mesh.envFrom }}
          envFrom:
{{- toYaml . | nindent 12 }}
          {{- end }}
          args:
            - "--entryPoints.readiness.address=:1081"
            - "--entryPoints.liveness.address=:1082"
            {{- range $i, $port := untilStep 5000 ((add (.Values.limits.http|int) 5000)|int) 1 }}
            - {{ printf "\"--entryPoints.http-%d.address=:%d\"" $port $port }}
            - {{ printf "\"--entryPoints.http-%d.forwardedHeaders.insecure=true\"" $port }}
            {{- end }}
            {{- range $i, $port := untilStep 10000 ((add (.Values.limits.tcp|int) 10000)|int) 1 }}
            - {{ printf "\"--entryPoints.tcp-%d.address=:%d\"" $port $port }}
            - {{ printf "\"--entryPoints.tcp-%d.forwardedHeaders.insecure=true\"" $port }}
            {{- end }}
            {{- range $i, $port := untilStep 15000 ((add (.Values.limits.udp|int) 15000)|int) 1 }}
            - {{ printf "\"--entryPoints.udp-%d.address=:%d/udp\"" $port $port }}
            {{- end }}
            - {{ printf "--providers.http.endpoint=http://maesh-controller.%s.svc.%s:9000/api/configuration/current" .Release.Namespace (default "cluster.local" .Values.clusterDomain) | quote }}
            {{- if .Values.mesh.pollInterval }}
            - "--providers.http.pollInterval={{ .Values.mesh.pollInterval }}"
            {{- end }}
            {{- if .Values.mesh.pollTimeout }}
            - "--providers.http.pollTimeout={{ .Values.mesh.pollTimeout }}"
            {{- end }}
            {{- if .Values.tracing.jaeger.enabled }}
              {{- if .Values.tracing.jaeger.localagenthostport }}
            - "--tracing.jaeger.localagenthostport={{ .Values.tracing.jaeger.localagenthostport }}"
              {{- else }}
            - {{ printf "--tracing.jaeger.localagenthostport=jaeger-agent.%s.svc.%s:6831" .Release.Namespace (default "cluster.local" .Values.clusterDomain) | quote }}
              {{- end }}
              {{- if .Values.tracing.jaeger.localagenthostport }}
            - "--tracing.jaeger.samplingserverurl={{ .Values.tracing.jaeger.samplingserverurl }}"
              {{- else }}
            - {{ printf "--tracing.jaeger.samplingserverurl=http://jaeger-agent.%s.svc.%s:5778/sampling" .Release.Namespace (default "cluster.local" .Values.clusterDomain) | quote }}
              {{- end }}
            {{- end }}
            {{- if .Values.tracing.datadog }}
              {{- if .Values.tracing.datadog.localagenthostport }}
            - "--tracing.datadog.localagenthostport={{ .Values.tracing.datadog.localagenthostport }}"
              {{- end }}
              {{- if .Values.tracing.datadog.debug }}
            - "--tracing.datadog.debug=true"
              {{- end }}
              {{- if .Values.tracing.datadog.globalTag }}
            - "--tracing.datadog.globalTag={{ .Values.tracing.datadog.globalTag }}"
              {{- end }}
              {{- if .Values.tracing.datadog.prioritySampling }}
            - "--tracing.datadog.prioritySampling=true"
              {{- end }}
            {{- end }}
            {{- if .Values.tracing.zipkin }}
              {{- if .Values.tracing.zipkin.httpEndpoint }}
            - "--tracing.zipkin.httpEndpoint={{ .Values.tracing.zipkin.httpEndpoint }}"
              {{- end }}
              {{- if .Values.tracing.zipkin.sameSpan }}
            - "--tracing.zipkin.sameSpan=true"
              {{- end }}
              {{- if .Values.tracing.zipkin.id128Bit }}
            - "--tracing.zipkin.id128Bit=true"
              {{- end }}
              {{- if .Values.tracing.zipkin.sampleRate }}
            - "--tracing.zipkin.sampleRate={{ .Values.tracing.zipkin.sampleRate }}"
              {{- end }}
            {{- end }}
            {{- if .Values.tracing.instana }}
              {{- if .Values.tracing.instana.localAgentHost }}
            - "--tracing.instana.localAgentHost={{ .Values.tracing.instana.localAgentHost }}"
              {{- end }}
              {{- if .Values.tracing.instana.localAgentPort }}
            - "--tracing.instana.localAgentPort={{ .Values.tracing.instana.localAgentPort }}"
              {{- end }}
              {{- if .Values.tracing.instana.logLevel }}
            - "--tracing.instana.logLevel={{ .Values.tracing.instana.logLevel }}"
              {{- end }}
            {{- end }}
            {{- if .Values.tracing.haystack }}
              {{- if .Values.tracing.haystack.localAgentHost }}
            - "--tracing.haystack.localAgentHost={{ .Values.tracing.haystack.localAgentHost }}"
              {{- end }}
              {{- if .Values.tracing.haystack.localAgentPort }}
            - "--tracing.haystack.localAgentPort={{ .Values.tracing.haystack.localAgentPort }}"
              {{- end }}
              {{- if .Values.tracing.haystack.globalTag }}
            - "--tracing.haystack.globalTag={{ .Values.tracing.haystack.globalTag }}"
              {{- end }}
              {{- if .Values.tracing.haystack.traceIDHeaderName }}
            - "--tracing.haystack.traceIDHeaderName={{ .Values.tracing.haystack.traceIDHeaderName }}"
              {{- end }}
              {{- if .Values.tracing.haystack.parentIDHeaderName }}
            - "--tracing.haystack.parentIDHeaderName={{ .Values.tracing.haystack.parentIDHeaderName }}"
              {{- end }}
              {{- if .Values.tracing.haystack.spanIDHeaderName }}
            - "--tracing.haystack.spanIDHeaderName={{ .Values.tracing.haystack.spanIDHeaderName }}"
              {{- end }}
              {{- if .Values.tracing.haystack.baggagePrefixHeaderName }}
            - "--tracing.haystack.baggagePrefixHeaderName={{ .Values.tracing.haystack.baggagePrefixHeaderName }}"
              {{- end }}
            {{- end }}
            - "--api.dashboard=false"
            - "--api.insecure"
            - "--ping"
            {{- if .Values.mesh.forwardingTimeouts }}
              {{- if .Values.mesh.forwardingTimeouts.dialTimeout }}
            - "--serversTransport.forwardingTimeouts.dialTimeout={{ .Values.mesh.forwardingTimeouts.dialTimeout }}"
              {{- end }}
              {{- if .Values.mesh.forwardingTimeouts.responseHeaderTimeout }}
            - "--serversTransport.forwardingTimeouts.responseHeaderTimeout={{ .Values.mesh.forwardingTimeouts.responseHeaderTimeout }}"
              {{- end }}
              {{- if .Values.mesh.forwardingTimeouts.idleConnTimeout }}
            - "--serversTransport.forwardingTimeouts.idleConnTimeout={{ .Values.mesh.forwardingTimeouts.idleConnTimeout }}"
              {{- end }}
            {{- end }}
            {{- if or .Values.mesh.logLevel .Values.logLevel }}
            - "--log.level={{ or .Values.mesh.logLevel .Values.logLevel }}"
            {{- end }}
            {{- if or .Values.mesh.logFormat .Values.logFormat }}
            - "--log.format={{ or .Values.mesh.logFormat .Values.logFormat }}"
            {{- end }}
            {{- if .Values.metrics.prometheus.enabled }}
            - "--metrics.prometheus"
            {{- end }}
            {{- if .Values.metrics.datadog }}
            - "--metrics.datadog=true"
              {{- if .Values.metrics.datadog.address }}
            - "--metrics.datadog.address={{ .Values.metrics.datadog.address }}"
              {{- end }}
              {{- if .Values.metrics.datadog.addEntrypointsLabels }}
            - "--metrics.datadog.addEntryPointsLabels=true"
              {{- end }}
              {{- if .Values.metrics.datadog.addServiceLabels }}
            - "--metrics.datadog.addServicesLabels=true"
              {{- end }}
              {{- if .Values.metrics.datadog.pushInterval }}
            - "--metrics.datadog.pushInterval={{ .Values.metrics.datadog.pushInterval }}"
              {{- end }}
            {{- end }}
            {{- if .Values.metrics.influxdb }}
            - "--metrics.influxdb=true"
              {{- if .Values.metrics.influxdb.address }}
            - "--metrics.influxdb.address={{ .Values.metrics.influxdb.address }}"
              {{- end }}
              {{- if .Values.metrics.influxdb.protocol }}
            - "--metrics.influxdb.protocol={{ .Values.metrics.influxdb.protocol }}"
              {{- end }}
              {{- if .Values.metrics.influxdb.database }}
            - "--metrics.influxdb.database={{ .Values.metrics.influxdb.database }}"
              {{- end }}
              {{- if .Values.metrics.influxdb.retentionPolicy }}
            - "--metrics.influxdb.retentionPolicy={{ .Values.metrics.influxdb.retentionPolicy }}"
              {{- end }}
              {{- if .Values.metrics.influxdb.username }}
            - "--metrics.influxdb.username={{ .Values.metrics.influxdb.username }}"
              {{- end }}
              {{- if .Values.metrics.influxdb.password }}
            - "--metrics.influxdb.password={{ .Values.metrics.influxdb.password }}"
              {{- end }}
              {{- if .Values.metrics.influxdb.addEntrypointsLabels }}
            - "--metrics.influxdb.addEntryPointsLabels=true"
              {{- end }}
              {{- if .Values.metrics.influxdb.addServiceLabels }}
            - "--metrics.influxdb.addServicesLabels=true"
              {{- end }}
              {{- if .Values.metrics.influxdb.pushInterval }}
            - "--metrics.influxdb.pushInterval={{ .Values.metrics.influxdb.pushInterval }}"
              {{- end }}
            {{- end }}
            {{- if .Values.metrics.statsd }}
            - "--metrics.statsd=true"
              {{- if .Values.metrics.statsd.address }}
            - "--metrics.statsd.address={{ .Values.metrics.statsd.address }}"
              {{- end }}
              {{- if .Values.metrics.statsd.addEntrypointsLabels }}
            - "--metrics.statsd.addEntryPointsLabels=true"
              {{- end }}
              {{- if .Values.metrics.statsd.addServiceLabels }}
            - "--metrics.statsd.addServicesLabels=true"
              {{- end }}
              {{- if .Values.metrics.statsd.pushInterval }}
            - "--metrics.statsd.pushInterval={{ .Values.metrics.statsd.pushInterval }}"
              {{- end }}
            {{- end }}
            {{- with .Values.mesh.additionalArguments }}
            {{- range . }}
            - {{ . | quote }}
            {{- end }}
            {{- end }}
          ports:
            - name: readiness
              containerPort: 1081
            - name: liveness
              containerPort: 1082
            - name: api
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /ping
              port: readiness
            initialDelaySeconds: 3
            periodSeconds: 1
          livenessProbe:
            tcpSocket:
              port: liveness
            initialDelaySeconds: 3
            periodSeconds: 1
          resources:
            requests:
              memory: {{ .Values.mesh.resources.request.mem }}
              cpu: {{ .Values.mesh.resources.request.cpu }}
            limits:
              memory: {{ .Values.mesh.resources.limit.mem }}
              cpu: {{ .Values.mesh.resources.limit.cpu }}
