---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: maesh-mesh
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name | quote }}
    chart: {{ include "maesh.chartLabel" . | quote }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name | quote }}
      component: maesh-mesh
      release: {{ .Release.Name | quote }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name | quote }}
        component: maesh-mesh
        release: {{ .Release.Name | quote }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      serviceAccountName: maesh-mesh
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      terminationGracePeriodSeconds: 30
      {{- with .Values.mesh.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.mesh.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- if .Values.tracing.deploy }}
      initContainers:
        - name: wait-for-jaeger-init
          image: {{ .Values.tracing.jaeger.image.name | quote }}
          imagePullPolicy: {{ .Values.tracing.jaeger.image.pullPolicy | default "IfNotPresent" }}
          args: ["service", "-lapp.kubernetes.io/name=jaeger-agent"]
          resources:
            requests:
              memory: "10Mi"
              cpu: "50m"
            limits:
              memory: "20Mi"
              cpu: "100m"
      {{- end }}
      containers:
        - name: maesh-mesh
          image: {{ include "maesh.meshImage" . | quote }} 
          imagePullPolicy: {{ .Values.mesh.image.pullPolicy | default "IfNotPresent" }}
          args:
            - "--entryPoints.readiness.address=:1081"
            - "--entryPoints.liveness.address=:1082"
          {{- range $i, $e := until (.Values.limits.http|int) }}
            - {{ printf "\"--entryPoints.http-%d.address=:%d\"" (add $i 5000) (add $i 5000) }}
          {{- end }}
          {{- range $i, $e := until (.Values.limits.tcp|int) }}
            - {{ printf "\"--entryPoints.tcp-%d.address=:%d\"" (add $i 10000) (add $i 10000) }}
          {{- end }}
            - "--providers.rest"
            - "--providers.rest.insecure"
            {{- if .Values.tracing.jaeger.enabled }}
              {{- if .Values.tracing.jaeger.localagenthostport }}
            - "--tracing.jaeger.localagenthostport={{ .Values.tracing.jaeger.localagenthostport }}"
              {{- else }}
            - {{ printf "--tracing.jaeger.localagenthostport=jaeger-agent.%s.svc.%s:6831" .Release.Namespace (default "cluster.local" .Values.clusterDomain) | quote }}
              {{- end }}
              {{- if .Values.tracing.jaeger.localagenthostport }}
            - "--tracing.jaeger.samplingserverurl={{ .Values.tracing.jaeger.samplingserverurl }}"
              {{- else }}
            - {{ printf "--tracing.jaeger.samplingserverurl=http://jaeger-agent.%s.svc.%s:5778/sampling" .Release.Namespace (default "cluster.local" .Values.clusterDomain) | quote }}
              {{- end }}
            {{- end }}
            {{- if .Values.tracing.datadog }}
              {{- if .Values.tracing.datadog.localagenthostport }}
            - "--tracing.datadog.localagenthostport={{ .Values.tracing.datadog.localagenthostport }}"
              {{- end }}
              {{- if .Values.tracing.datadog.debug }}
            - "--tracing.datadog.debug=true"
              {{- end }}
              {{- if .Values.tracing.datadog.globalTag }}
            - "--tracing.datadog.globalTag={{ .Values.tracing.datadog.globalTag }}"
              {{- end }}
              {{- if .Values.tracing.datadog.prioritySampling }}
            - "--tracing.datadog.prioritySampling=true"
              {{- end }}
            {{- end }}
            - "--api.dashboard"
            - "--api.insecure"
            - "--ping"
            - "--log.level={{ .Values.mesh.logging }}"
            {{- if .Values.metrics.prometheus.enabled }}
            - "--metrics.prometheus"
            {{- end }}
            {{- if .Values.metrics.datadog.enabled }}
            - "--metrics.datadog=true"
              {{- if .Values.metrics.datadog.address }}
            - "--metrics.datadog.address={{ .Values.metrics.datadog.address }}"
              {{- end }}
              {{- if .Values.metrics.datadog.addEntrypointsLabels }}
            - "--metrics.datadog.addEntryPointsLabels=true"
              {{- end }}
              {{- if .Values.metrics.datadog.addServiceLabels }}
            - "--metrics.datadog.addServicesLabels=true"
              {{- end }}
              {{- if .Values.metrics.datadog.pushInterval }}
            - "--metrics.datadog.pushInterval={{ .Values.metrics.datadog.pushInterval }}"
              {{- end }}
            {{- end }}
          ports:
            - name: readiness
              containerPort: 1081
            - name: liveness
              containerPort: 1082
            - name: api
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /ping
              port: readiness
            initialDelaySeconds: 3
            periodSeconds: 1
          livenessProbe:
            tcpSocket:
              port: liveness
            initialDelaySeconds: 3
            periodSeconds: 1
          resources:
            requests:
              memory: {{ .Values.mesh.resources.request.mem }}
              cpu: {{ .Values.mesh.resources.request.cpu }}
            limits:
              memory: {{ .Values.mesh.resources.limit.mem }}
              cpu: {{ .Values.mesh.resources.limit.cpu }}
