---
apiVersion: v1
kind: Service
metadata:
  name: maesh-mesh-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: mesh-api
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: mesh-api
      targetPort: api
  selector:
    component: maesh-mesh
