---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: maesh-mesh
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name | quote}}
    chart: {{ include "maesh.chartLabel" . | quote}}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
automountServiceAccountToken: false
